apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-pttest-rs
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pttest
  template:
    metadata:
      name: nginx-templ
      labels:
        app: nginx-pttest
    spec:
      containers:
      - name: nginx-pttest
        image: nginx
        ports:
          - containerPort: 80
